### ISSUE TITLE
Issue in evaluation script

### ISSUE THREAD

**Issue by nguepigit2020** [machelreid/afromt#2]
Hello dear Machelreidm, I followed the instructions in the afromt repository to the end, but the evaluation returns 0 for both metrics. 
**cat tgt | sacremoses detokenize > tgt.tmp 2> /dev/null
cat hyp | sacremoses detokenize > hyp.tmp 2> /dev/null**
lThe two lines of code above are the cause because after executing these two lines the **tgt.tmp** and **hyp.tmp** files are empty.
ref: https://github.com/machelreid/afromt/blob/main/eval_bleu_chrf.sh#L5
I am hereby asking for your suggestions.
Cordially

**Comment by machelreid** [comment]
I just tried the script on my laptop and it seems there isn't an issue directly with the eval script itself. Could you check if there is a difference in format with the file you are feeding for evaluation? Feel free to upload it here, so I can take a look.

**Comment by nguepigit2020** [comment]
See below the content of my generation.log file

<img width="1323" alt="Screenshot 2023-01-21 at 15 16 08" src="https://user-images.githubusercontent.com/57442768/213873827-bfa9d034-9a70-4112-8cc4-b5e6899b9fa6.png">

you can also see the content of the script below

<img width="1065" alt="Screenshot 2023-01-21 at 15 17 57" src="https://user-images.githubusercontent.com/57442768/213873796-9ff28d79-d804-49eb-bb78-821698207c73.png">

**Comment by machelreid** [comment]
If you do:
```
!cat generation.log | grep ^T | sort -V | cut -f2 | head -5
```
and
```
!cat generation.log | grep ^H | sort -V | cut -f3 | head -5
```
could you show me what comes out?

Thanks.

**Comment by nguepigit2020** [comment]
!cat generation.log | grep ^T | sort -V | cut -f2 | head -5 output:

<img width="1728" alt="Screenshot 2023-01-21 at 17 00 38" src="https://user-images.githubusercontent.com/57442768/213878213-41e68f6d-6421-4f37-8850-f08895d092ab.png">

cat generation.log | grep ^H | sort -V | cut -f3 | head -5 output:

<img width="1698" alt="Screenshot 2023-01-21 at 17 01 48" src="https://user-images.githubusercontent.com/57442768/213878249-0edbda96-2ddb-4c53-ad7a-1403cdb6ec46.png">

**Comment by nguepigit2020** [comment]
It okay, after intalling sacremoses it working fine now. Thanks
