### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by nguepigit2020** [machelreid/afromt#3]
I'm having the below error during the training process. 
<img width="1725" alt="Screenshot 2023-01-19 at 21 57 14" src="https://user-images.githubusercontent.com/57442768/213579488-dc343e30-0c1f-46a6-950d-2661db41b495.png">

Below picture is the content of training script

<img width="1584" alt="Screenshot 2023-01-19 at 22 00 37" src="https://user-images.githubusercontent.com/57442768/213579859-570f9705-0421-436d-8f12-af743dda30b0.png">

**Comment by machelreid** [comment]
Hi there, I think this should be solved by including --max-source-positions
512 and --max-target-positions 512. Let me know if this works!

**Comment by nguepigit2020** [comment]
Thanks for your support,
